export const EXAMPLE_PATH = 'elbiforleni.com'
export const CMS_NAME = 'Sanity'
export const CMS_URL = 'https://sanity.io/'
export const HOME_OG_IMAGE_URL = 'assets/homepage/lb-for-leni-logo.jpeg'
export const HOME_OG_DESC = 'Nagkakaisang mga taga-suporta ni Vice PRESIDENT Leni Robredo at Sen. Kiko Pangilinan sa Los Baños, Laguna.'
export const HOME_OG_TITLE = 'LB for Leni and Kiko'
export const SITE_URL = 'https://elbiforleni.com/'
export const SITE_TITLE = 'LB for Leni and Kiko'